teleop_twist_joy:
  ros__parameters:
    publish_stamped_twist: True
    use_sim_time: False
    axis_linear.x: 1
    axis_linear.y: 3
    axis_angular.yaw: 0
    enable_button: 4
    enable_turbo_button: 5
    scale_linear.x: 0.4
    scale_angular.yaw: 0.6
    scale_linear_turbo.x: 1.0
    scale_angular_turbo.yaw: 1.2
